### ISSUE TITLE
Fix the keyUrl endpoint handling in fhevmjs

### ISSUE THREAD

**Issue by jatZama** [zama-ai/fhevmjs#115]
2 sub-issues to fix:
1/ https://zama-ai.slack.com/archives/C065F16D5U3/p1729527276213009?thread_ts=1729526777.909589&cid=C065F16D5U3
2/ https://zama-ai.slack.com/archives/C046UJ6QYBA/p1729527173896099 : after new patch release of node-tfhe tomorrow

**Comment by RomanBredehoft** [comment]
this has been done
