### ISSUE TITLE
Module not found: Can't resolve 'tfhe_bg.wasm'

### ISSUE THREAD

**Issue by tnkshuuhei** [zama-ai/fhevmjs#62]
I created Next.js project by following this [tutorial](https://docs.zama.ai/fhevm/guides/webapp) but got this error.
and also seems fhevm.js v0.4.x doesn't have the export `initFhevm`

```
 ⨯ ./node_modules/.pnpm/fhevmjs@0.4.0/node_modules/fhevmjs/lib/web.js:7685:0
Module not found: Can't resolve 'tfhe_bg.wasm'
```

**Comment by immortal-tofu** [comment]
Hello!
First, you should use 0.3.2 for now. The new version of fhevmjs has been published a little bit in advance, but the new fhEVM is not released yet (but will be soon).
Did you try to use the same [config we use in the template](https://github.com/zama-ai/fhevmjs-next-template/blob/main/next.config.js)?

**Comment by tnkshuuhei** [comment]
I appreciate your help! that config solved the resolver issue.

but now, I'm getting error when trying to create instance.
FYI, Ive got the same error when I used next.js template!

im trying to create instance within contextAPI. seems public key is not proper and instance is undefined...
<img width="167" alt="Screenshot 2024-04-17 at 21 15 37" src="https://github.com/zama-ai/fhevmjs/assets/67859510/536d47bd-ecbe-4813-80ae-fae59c60fb66">

<img width="966" alt="Screenshot 2024-04-17 at 21 13 50" src="https://github.com/zama-ai/fhevmjs/assets/67859510/da0c69c6-4ba9-4b28-ba97-28067e892382">

```typescript
"use client";
import { useEthersProvider } from "@/hooks/useEthers";
import { FhevmInstance, initFhevm } from "fhevmjs";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { useAccount, useChainId } from "wagmi";
import { createInstance } from "fhevmjs/web";

const stateContext = createContext<any>(null);

export const StateProvider = ({ children }: { children: React.ReactNode }) => {
  const [instance, setInstance] = useState<FhevmInstance | undefined>();
  const { address } = useAccount();
  const chainId = 8009;
  const provider = useEthersProvider({ chainId });
  // const chainId = useChainId();

  useMemo(async () => {
    await initFhevm();
    createFhevmInstance();
    console.log("fhevm initialized");
  }, [provider, address]);
  const createFhevmInstance = async () => {
    const publicKey = await provider?.call({
      from: null,
      to: "0x0000000000000000000000000000000000000044",
    });
    console.log("publicKey", publicKey);
    const instance = await createInstance({ chainId, publicKey } as {
      chainId: number;
      publicKey: string;
    });
    console.log("instance", instance);
    setInstance(instance);
  };
  const getTokenSignature = async (
    contractAddress: string,
    userAddress: string
  ) => {
    if (instance!.hasKeypair(contractAddress)) {
      return instance!.getTokenSignature(contractAddress)!;
    } else {
      const { publicKey, token } = instance!.generateToken({
        verifyingContract: contractAddress,
      });
      const params = [userAddress, JSON.stringify(token)];
      const signature: string = await window.ethereum.request({
        method: "eth_signTypedData_v4",
        params,
      });
      instance!.setTokenSignature(contractAddress, signature);
      return { signature, publicKey };
    }
  };

  return (
    <stateContext.Provider
      value={{
        getTokenSignature,
        createFhevmInstance,
        instance,
      }}
    >
      {children}
    </stateContext.Provider>
  );
};

export const StateContext = () => useContext(stateContext);
```

**Comment by tnkshuuhei** [comment]
@immortal-tofu

**Comment by immortal-tofu** [comment]
This error is because you're not using a compatible version between the network you're using and the version of fhevmjs. As of today:
- Zama devnet needs fhevmjs 0.3.2
- INCO devnet needs fhevmjs 0.4.0
- Local node in hardhat template needs 0.3.2

**Comment by tnkshuuhei** [comment]
@immortal-tofu I upgraded to fhevmjs@0.3.2 but still getting the same error.

**Comment by immortal-tofu** [comment]
From which network did you get the public blockchain key?

**Comment by tnkshuuhei** [comment]
@immortal-tofu im trying to get pubKey from zamadevnet as I showed above code!

**Comment by immortal-tofu** [comment]
You're using the wrong precompiles address. Take a look at this example https://docs.zama.ai/fhevm/v/0.3-2/client-sdk/getting_started/browser

**Comment by immortal-tofu** [comment]
You're right. We've made few mistakes regarding the upcoming release because we released some packages and we didn't release others. Everything will be fixed in the coming days, but for now:
- Use this version of hardhat template which uses correct versions of fhevmjs (you can update fhevmjs to 0.3.2 since it's using 0.3.1, but this minor just include a bugfix for CLI) https://github.com/zama-ai/fhevm-hardhat-template/tree/bb0d8267e1325500bb577754d17c35b94ff7efa6
- Use fhevmjs 0.3.2 and fhevm 0.3.0

**Comment by tnkshuuhei** [comment]
@immortal-tofu 
gotcha! so which version of dev node should be used?
you said dev node should be v0.3.2 but I can't find that version....
current hardhat template is using v0.3.0-0, and [this](https://github.com/zama-ai/fhevm-hardhat-template/tree/bb0d8267e1325500bb577754d17c35b94ff7efa6) is using v0.2.4
```
> docker run -i -p 8545:8545 -p 8546:8546 --rm --name fhevm ghcr.io/zama-ai/ethermint-dev-node:v0.3.2

Unable to find image 'ghcr.io/zama-ai/ethermint-dev-node:v0.3.2' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```

**Comment by immortal-tofu** [comment]
Docker image doesn't follow the versioning above. You can use the 0.2.4 used in the hardhat template 👍
